CREATE TABLE ANYONE.GROUPS (
  GROUP_ID VARCHAR(40) NOT NULL,
  GROUP_NAME VARCHAR(40),
  PRIMARY KEY (GROUP_ID));

CREATE TABLE ANYONE.USERS (
  USER_ID VARCHAR(40) NOT NULL,
  USER_NAME VARCHAR(40),
  PASSWORD VARCHAR(40) NOT NULL,
  PHONE VARCHAR(40),
  CREATED TIMESTAMP NOT NULL,
  LAST_LOGIN TIMESTAMP,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  GROUP_ID VARCHAR(40) NOT NULL,
  ROLE VARCHAR(40) NOT NULL,
  PRIMARY KEY (USER_ID));
  
CREATE TABLE ANYONE.GOODS (
  GOODS_ID VARCHAR(40) NOT NULL,
  GOODS_NUMBER VARCHAR(40) NOT NULL,
  GOODS_NAME VARCHAR(40),
  GROUP_ID VARCHAR(40) NOT NULL,
  QTY DOUBLE DEFAULT 0,
  CREATED TIMESTAMP NOT NULL,
  PRIMARY KEY (GOODS_ID));
  
CREATE TABLE ANYONE.GOODS_IN (
  GOODSIN_ID VARCHAR(40) NOT NULL,
  USER_ID VARCHAR(40) NOT NULL,
  PRICE DOUBLE DEFAULT 0,
  QTY DOUBLE DEFAULT 0,
  CREATED TIMESTAMP NOT NULL,
  EXPRESS_NUMBER VARCHAR(40) NOT NULL,
  FEE DOUBLE DEFAULT 0,
  GOODS_ID VARCHAR(40) NOT NULL,
  PRIMARY KEY (GOODSIN_ID));
  
CREATE TABLE ANYONE.GOODS_OUT (
  GOODSOUT_ID VARCHAR(40) NOT NULL,
  USER_ID VARCHAR(40) NOT NULL,
  PRICE DOUBLE DEFAULT 0,
  QTY DOUBLE DEFAULT 0,
  CREATED TIMESTAMP NOT NULL,
  EXPRESS_NUMBER VARCHAR(40) NOT NULL,
  FEE DOUBLE DEFAULT 0,
  GOODS_ID VARCHAR(40) NOT NULL,
  PRIMARY KEY (GOODSOUT_ID));
  
CREATE TABLE ANYONE.GOODS_RETURN (
  GOODSRETURN_ID VARCHAR(40) NOT NULL,
  GOODSOUT_ID VARCHAR(40) NOT NULL,
  QTY DOUBLE DEFAULT 0,
  CREATED TIMESTAMP NOT NULL,
  EXPRESS_NUMBER VARCHAR(40) NOT NULL,
  FEE DOUBLE DEFAULT 0,
  REASON VARCHAR(300) NOT NULL,
  PRIMARY KEY (GOODSRETURN_ID));